name: juliac

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '~1.12.0-rc1'
          arch: x64

      - name: Cache Julia artifacts
        uses: julia-actions/cache@v2

      - name: Build executable
        working-directory: juliac
        run: |
          make

      - name: Test executable
        working-directory: juliac
        run: |
          ./mainc

      - name: Package artifacts
        working-directory: juliac
        run: |
          mkdir -p ../artifacts
          cp mainc ../artifacts/
          cp libposeest.so ../artifacts/
          cp -r julia ../artifacts/
          cp libjulia.so* ../artifacts/ 2>/dev/null || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: juliac-build
          path: artifacts/

  test-without-julia:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: juliac-build
          path: artifacts/

      - name: Make executable runnable
        run: |
          chmod +x artifacts/mainc

      - name: Test executable without Julia
        run: |
          cd artifacts
          ./mainc
