name: CI – PackageCompiler.jl

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Pick the OSes you care about
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Add / change Julia versions here
        julia-version: ["1.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}

      - name: Cache Julia packages
        uses: julia-actions/cache@v2

      - name: Install dependencies
        working-directory: pkgcompiler
        run: |
          julia --project -e 'using Pkg; Pkg.instantiate()'

      - name: Run PackageCompiler
        working-directory: pkgcompiler
        run: |
          julia --project build.jl
